"""Pydantic models for Tracker system data structures."""

from datetime import datetime
from typing import List, Optional, Dict, Any, Literal
from uuid import UUID, uuid4
from pydantic import BaseModel, Field, validator
from enum import Enum

class Platform(str, Enum):
    LINUX = "linux"
    WINDOWS = "windows"
    MACOS = "macos"
    TERMUX = "termux"

class CommandType(str, Enum):
    SHOW_MESSAGE = "SHOW_MESSAGE"
    PLAY_CHIME = "PLAY_CHIME"
    INCREASE_HEARTBEAT = "INCREASE_HEARTBEAT"
    LOCK_SCREEN = "LOCK_SCREEN"
    PING = "PING"

class CommandStatus(str, Enum):
    QUEUED = "QUEUED"
    ACKED = "ACKED"
    DONE = "DONE"
    FAILED = "FAILED"

class AlertType(str, Enum):
    NO_HEARTBEAT = "NO_HEARTBEAT"
    NEW_IP = "NEW_IP"
    NEW_WIFI = "NEW_WIFI"

class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"

class WiFiNetwork(BaseModel):
    """WiFi network information."""
    ssid: str
    bssid: str
    signal: int = Field(..., ge=-100, le=0)

class Location(BaseModel):
    """Geographic location information."""
    city: Optional[str] = None
    region: Optional[str] = None
    country: Optional[str] = None
    lat: Optional[float] = None
    lon: Optional[float] = None

class TelemetryEvent(BaseModel):
    """Telemetry data from device."""
    seq: int = Field(..., ge=0)
    ts: datetime
    hostname: str
    os: str
    wifi: List[WiFiNetwork] = []
    battery: Optional[int] = Field(None, ge=0, le=100)
    meta: Dict[str, Any] = {}

class DeviceInfo(BaseModel):
    """Device information."""
    id: UUID = Field(default_factory=uuid4)
    owner_id: UUID
    display_name: str
    platform: Platform
    enrolled_at: datetime = Field(default_factory=datetime.utcnow)
    lost: bool = False
    last_seen_at: Optional[datetime] = None
    last_ip: Optional[str] = None
    last_asn: Optional[int] = None
    last_location: Optional[Location] = None
    meta: Dict[str, Any] = {}

class EnrollmentRequest(BaseModel):
    """Device enrollment request."""
    token: str
    pubkey: str  # Base64 encoded ed25519 public key
    platform: Platform
    display_name: str

class EnrollmentResponse(BaseModel):
    """Device enrollment response."""
    device_id: UUID
    device_token: str
    issued_at: datetime
    expires_at: Optional[datetime] = None

class Command(BaseModel):
    """Command for device to execute."""
    id: UUID = Field(default_factory=uuid4)
    device_id: UUID
    type: CommandType
    payload: Dict[str, Any] = {}
    status: CommandStatus = CommandStatus.QUEUED
    created_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = None
    must_ack: bool = True

class CommandAck(BaseModel):
    """Command acknowledgment from device."""
    status: CommandStatus
    details: Optional[str] = None

class Alert(BaseModel):
    """Alert generated by the system."""
    id: UUID = Field(default_factory=uuid4)
    device_id: UUID
    type: AlertType
    severity: AlertSeverity
    details: Dict[str, Any] = {}
    created_at: datetime = Field(default_factory=datetime.utcnow)
    resolved_at: Optional[datetime] = None

class Report(BaseModel):
    """Device tracking report."""
    device: DeviceInfo
    timeline: List[Dict[str, Any]]
    wifi_summary: List[Dict[str, Any]]
    commands: List[Command]
    ownership_proof: Dict[str, Any]

class ErrorResponse(BaseModel):
    """Standardized error response."""
    error: Dict[str, Any] = Field(...)
    
    @validator("error")
    def validate_error(cls, v):
        if "code" not in v or "message" not in v:
            raise ValueError("Error must have 'code' and 'message' fields")
        return v
